### ISSUE TITLE
Cannot write to Windows device

### ISSUE THREAD

**Issue by jviotti** [jhermsmeier/node-blockdevice#1]
I'm using the library to correctly override the MBR of an sd card on OS X, however I'm having trouble doing the same on Windows 8, as even when `write` returns the correct bytes written, the changes are not reflected on the disk.

``` js
var device = new BlockDevice({
  path: '\\\\.\\PhysicalDrive1',
  mode: 'w+',
  size: 512
});

device.write(0, myNewMBRBuffer, callback);
```

Did you try this yourself? I appreciate if you can give me any clues if you encountered the same issue.

**Comment by jhermsmeier** [comment]
Hey, sorry I never answered this – I guess you've figured it out some time in the past two years already.

The gibberish with the `MSDOS5.0` looks like a FAT Volume Boot Record to me – in this case probably the first sector of the FAT32 partition on the SD card, which is indeed not the wanted block.

I'm getting back to work on this module, and will do some fiddeling on Windows again soon, checking if and what changed about behavior and possibilities.

**Comment by jviotti** [comment]
Hi @jhermsmeier ,

No worries! We indeed discovered and fixed the issue. Turns out that Windows policies for raw I/O to physical drives tells us that we can write to the drive without errors only in the following cases (this was linked by you in one of the first comments):

- The sector we're trying to write to is the first sector of the drive.
- The drive has no file system.

We're using `diskpart.exe` `clean` command to erase the file system from the drive before writing to it, and it works great.

All this work resulted in Etcher (http://www.etcher.io) and open source image writer based on Electron.

**Comment by lurch** [comment]
...and see also https://resin.io/blog/the-perils-of-writing-disk-images-on-windows/

**Comment by jorangreef** [comment]
@jviotti I've opened an issue in libuv to sort this out by exposing a `UV_FS_O_EXLOCK` flag, which will lock the block device for exclusive access to allow writing:

https://github.com/libuv/libuv/issues/1605

**Comment by lurch** [comment]
@jhermsmeier Did you ever get round to trying out the Etcher software that @jviotti mentioned? :laughing:

**Comment by jviotti** [comment]
Closing stale issues
